language: rust
rust: nightly
cache: cargo
before_install:
  - wget "http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl"
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export PATH="/home/travis/.cargo/bin:${DEVKITARM}/bin:$PATH"
install:
  - perl devkitARMupdate.pl
  - curl "https://sh.rustup.rs" -sSf | sh -s -- --default-toolchain=nightly -y;
  - rustup component add rust-src
  - cargo install --force xargo
script:
  - make build
