language: generic
branches:
  only:
    - master
before_install:
  - export DEVKITPRO="$HOME/devkitPro"
  - export DEVKITARM="$DEVKITPRO/devkitARM"
  - export PATH="$HOME/.cargo/bin:${DEVKITARM}/bin:$PATH"
install:
  - wget "http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl"
  - perl devkitARMupdate.pl
  - curl "https://sh.rustup.rs" -sSf | sh -s -- --default-toolchain=nightly -y;
  - rustup component add rust-src
  - cargo install --force xargo
script:
  - make build
